- name: main
  hosts: servers
  remote_user: root

  tasks:
  - name: append timestamp to file
    ansible.builtin.shell: date >> checkins.txt

  - name: have git
    ansible.builtin.package:
      name: git
      state: present

  - name: have apache
    ansible.builtin.package:
      name: apache2
      state: present

  - name: have nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
