- name: main
  hosts: all
  remote_user: root

  tasks:
  - name: append timestamp to file
    ansible.builtin.shell: date >> checkins.txt

  - name: have git
    ansible.builtin.package:
      name: git
      state: present

  - name: have apache
    ansible.builtin.package:
      name: apache2
      state: present

  - name: have nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: have ssh keypair
    community.crypto.openssh_keypair:
      path: /root/.ssh/id_rsa

  - name: read ssh public key
    ansible.builtin.slurp:
      src: /root/.ssh/id_rsa.pub
    register: ssh_public_key

  - name: post ssh public key to github
    uri:
      url: "https://api.github.com/user/keys"
      method: POST
      headers:
        Accept: "application/vnd.github+json"
        Authorization: "Bearer {{ github_token }}"
        X-GitHub-Api-Version: "2022-11-28"
      body_format: json
      body:
        title: "profile-iac-ansible"
        key: "{{ ssh_public_key['content'] | b64decode }}"
      status_code: [201, 422]
      return_content: true
    delegate_to: localhost
    register: response
    failed_when: >
      response.status == 422 and
      response.json.errors[0].message != 'key is already in use'

  - name: have profile repo
    ansible.builtin.git:
      repo: git@github.com:tomiplaz/profile.git
      dest: /var/www/profile
      accept_newhostkey: true
