- name: letsencrypt
  hosts: all
  remote_user: root

  vars:
    acme_challenge_type: http-01
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    letsencrypt_dir: /etc/letsencrypt
    letsencrypt_keys_dir: /etc/letsencrypt/keys
    letsencrypt_csrs_dir: /etc/letsencrypt/csrs
    letsencrypt_certs_dir: /etc/letsencrypt/certs
    letsencrypt_account_key: /etc/letsencrypt/account/account.key
    domain_name: tomiplaz.dev

  tasks:
  - name: create directories
    ansible.builtin.file:
      path: "/etc/letsencrypt/{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 711
    with_items:
    - account
    - certs
    - csrs
    - keys

  - name: generate account key
    shell: |
      if [ ! -f {{ letsencrypt_account_key }} ]; then
        openssl genrsa 4096 | tee {{ letsencrypt_account_key }};
      fi

  - name: generate private key
    shell: |
      openssl genrsa 4096 | tee {{ letsencrypt_keys_dir }}/{{ domain_name }}.key

  - name: generate csr
    shell: |
      openssl req
      -new
      -sha256
      -key "/etc/letsencrypt/keys/{{ domain_name }}.key"
      -subj "\"/CN={{ domain_name }}\""
      -reqexts SAN
      -config "<(cat /etc/ssl/openssl.cnf <(printf \"\n[SAN]\nsubjectAltName=DNS:{{ domain_name }},DNS:www.{{ domain_name }}\")) | tee {{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"

  - name: submit csr
    acme_certificate:
      acme_directory: "{{ acme_directory }}"
      acme_version: "{{ acme_version }}"
      account_key_src: "{{ letsencrypt_account_key }}"
      account_email: "{{ acme_email }}"
      terms_agreed: 1
      challenge: "{{ acme_challenge_type }}"
      csr: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
      dest: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
      fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.crt"
      remaining_days: 91
    register: acme_challenge_tomiplaz_dev

  - name: create acme-challenge directory
    file:
      path: /var/www/html/.well-known/acme-challenge
      state: directory
      owner: root
      group: root
      mode: 755

  - name: implement http-01 challenge files
    copy:
      content: "{{ acme_challenge_tomiplaz_dev['challenge_data'][item]['http-01']['resource_value'] }}"
      dest: "/var/www/html/{{ acme_challenge_tomiplaz_dev['challenge_data'][item]['http-01']['resource'] }}"
      owner: root
      group: root
      mode: 644
    with_items:
    - "{{ domain_name }}"
    - "www.{{ domain_name }}"

  - name: complete challenges
    acme_certificate:
      acme_directory: "{{ acme_directory }}"
      acme_version: "{{ acme_version }}"
      account_key_src: "{{ letsencrypt_account_key }}"
      account_email: "{{ acme_email }}"
      challenge: "{{ acme_challenge_type }}"
      csr: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
      dest: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
      chain_dest: "{{ letsencrypt_certs_dir }}/chain_{{ domain_name }}.crt"
      fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}"
      data: "{{ acme_challenge_tomiplaz_dev }}"
